################################################################################
#                                                                              #
# Preliminaries:                                                               #
#     sudo pip install pre-commit                                              #
#                                                                              #
# To setup:                                                                    #
#     pre-commit install                                                       #
#                                                                              #
# To use:                                                                      #
#     pre-commit run --all-files                                               #
#                                                                              #
# To update this file:                                                         #
#     pre-commit autoupdate                                                    #
#                                                                              #
################################################################################

ci:
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_commit_msg: "style: pre-commit fixes"

repos:
# Standard hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace

# Black, the code formatter, natively supports pre-commit
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black
    exclude: ^(docs)

# Sort your imports in a standard form
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
  - id: isort

# Upgrade older Python syntax
- repo: https://github.com/asottile/pyupgrade
  rev: v3.1.0
  hooks:
  - id: pyupgrade
    args: ["--py36-plus"]

# Changes tabs to spaces
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.3.1
  hooks:
  - id: remove-tabs
    exclude: ^(docs)

# CMake formatting
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.13
  hooks:
  - id: cmake-format
    additional_dependencies: [pyyaml]
    types: [file]
    files: (\.cmake|CMakeLists.txt)(.in)?$

# Suggested hook if you add a .clang-format file
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v14.0.6
  hooks:
  - id: clang-format
    types_or: [c++, c, python]
