name: Build

on:
  push:
    branches-ignore:
      - master
    paths:
      - "**/CMakeLists.txt"
      - "**/*.hpp"
      - "**/*.h"
      - "**/*.cpp"
      - ".github/workflows/*.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**/CMakeLists.txt"
      - "**/*.hpp"
      - "**/*.h"
      - "**/*.cpp"
      - ".github/workflows/*.yml"

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisiteries
        run: |
          apt-get update
          apt-get install -y cmake g++ libudev-dev pip pkg-config libgl-dev
          pip install conan

      - name: Install dependencies with conan
        run: |
          mkdir build
          cd build
          conan install .. --build=missing \
          -c tools.system.package_manager:mode=install \
          -c tools.system.package_manager:sudo=True

      - name: Build rtype binaries on Ubuntu (desktop)
        run: |
          cmake -DCMAKE_BUILD_TYPE=Release .. -G "Unix Makefiles"
          cmake --build  . -j 3

      - name: Check Ubuntu build (desktop)
        uses: andstor/file-existence-action@v1
        with:
          files: "r_type-client, r_type-server"

  build-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install vcpkg
        uses: friendlyanon/setup-vcpkg@v1
        with: { committish: "57d3194e702a2959e86a6748999ad71fc24f7922" }

      - name: Install sfml
        run: ${{env.VCPKG_ROOT}}/vcpkg.exe install --triplet x64-windows --debug

      - name: Build rtype on Windows (desktop)
        run: |
          cmake -B ${{github.workspace}}/build/ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE='${{env.VCPKG_ROOT}}/scripts/buildsystems/vcpkg.cmake' -DVCPKG_TARGET_TRIPLET=x86-windows-static
          cmake --build ${{github.workspace}}/build/ -j

      - name: Check Windows build (desktop)
        uses: andstor/file-existence-action@v1
        with:
          files: "r_type-client.exe, r_type-server.exe"
