name: Build

on:
  push:
    branches-ignore:
      - master
    paths:
      - "**/CMakeLists.txt"
      - "**/*.hpp"
      - "**/*.cpp"
      - ".github/workflows/*.yml"
  pull_request:
    branches:
      - master
    paths:
      - "**/CMakeLists.txt"
      - "**/*.hpp"
      - "**/*.cpp"
      - ".github/workflows/*.yml"

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install sfml prerequisites on Ubuntu
        run: |
          sudo apt install -y \
            build-essential \
            git \
            cmake \
            libasound2-dev \
            mesa-common-dev \
            libx11-dev \
            libxrandr-dev \
            libxi-dev \
            xorg-dev \
            libgl1-mesa-dev \
            libglu1-mesa-dev \
            libxext-dev \
            libxrender-dev \
            libxtst-dev \
            libxt-dev \
            libudev-dev \
            libfreetype6-dev \
            libopenal-dev \
            libvorbis-dev \
            libflac-dev \

      - name: Install sfml on Ubuntu
        run: |
          sudo apt install -y libsfml-dev

      - name: Build rtype binaries on Ubuntu (desktop)
        run: |
          mkdir build
          cd build && cmake ..
          cmake --build .

      - name: Check Ubuntu build (desktop)
        run: |
          test -f r-type_client
          test -f r-type_server

  build-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install sfml on Windows
        run: |
          git clone https://github.com/Microsoft/vcpkg.git $HOME/vcpkg
          cd $HOME/vcpkg
          bootstrap-vcpkg.bat
          vcpkg integrate install
          vcpkg install sfml

      - name: Build rtype on Windows (desktop)
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug
          cmake --build .

      - name: Check Windows build (desktop)
        run: |
          Test-Path r-type_client
          Test-Path r-type_server
