name: Formatter
on: push
jobs:
  lint:
    name: clang-format Code Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Clang Code Formatter
        uses: Mavrikant/clang-format-action@ubuntu-22.04
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

---
name: Build

on: push

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisiteries
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libudev-dev pip pkg-config libgl-dev

      - name: Install conan
        uses: turtlebrowser/get-conan@main

      - name: Build rtype binaries on Ubuntu (desktop)
        run: |
          mkdir build && cd build
          conan install .. --build=missing \
          -c tools.system.package_manager:mode=install \
          -c tools.system.package_manager:sudo=True
          cmake -DCMAKE_BUILD_TYPE=Release .. -G "Unix Makefiles"
          cmake --build  . -j 3

      - name: Check Ubuntu build (desktop)
        uses: andstor/file-existence-action@v1
        with:
          files: "r_type-client, r_type-server"

  build-on-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install conan
        uses: turtlebrowser/get-conan@main

      - name: Install dependencies
        run: |
          mkdir build && cd build
          conan install .. --build=missing -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True

      - name: Build rtype on Windows (desktop)
        run: |
          cd build/
          cmake .. -DCMAKE_BUILD_TYPE=Release -G 'Visual Studio 17 2022'
          cmake --build . -j 3

      - name: Check Windows build (desktop)
        uses: andstor/file-existence-action@v1
        with:
          files: "r_type-client.exe, r_type-server.exe"

  build-on-mac-m1:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Install brew
        run: |
          git clone https://github.com/Homebrew/brew homebrew
          eval "$(homebrew/bin/brew shellenv)"
          brew update --force --quiet
          chmod -R go-w "$(brew --prefix)/share/zsh"

      - name: Install conan
        run: |
          brew update
          brew install conan

      - name: Build rtype binaries on Mac (desktop)
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -G 'Unix Makefiles'
          cmake --build  . -j 3

      - name: Check MacOS build (desktop)
        uses: andstor/file-existence-action@v1
        with:
          files: "r_type-client, r_type-server"

  mirror:
    needs: [build-on-ubuntu, build-on-windows, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.EPI_REPO_URL }}
          ssh_private_key: ${{ secrets.EPI_MIRRORING_KEY }}
