name: Publish Documentation

on:
  workflow_dispatch:
    inputs:
      commit-name:
        description: "Name of the commit"
        required: true
        default: "[UPD] Documentation"

  deploy-documentation:
    runs-on: ubuntu-latest
    concurrency:
      group: "pages"
      cancel-in-progress: true
    permissions:
      contents: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.output.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: "recursive"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install graphviz doxygen -y

      - name: Build documentation
        run: |
          mkdir -p doc
          mkdir -p doc/output
          doxygen

      - name: Deploy documentation
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: doc/output/html
          commit-message: ${{ github.event.inputs.commit-name }}
          branch: gh-pages
