name: Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version string"
        required: true
        default: "0.0.0"
      body:
        description: "Release body"
        required: true
        default: "Release body"

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisiteries
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libudev-dev pip pkg-config libgl-dev

      - name: Install conan
        uses: turtlebrowser/get-conan@main

      - name: Build rtype binaries on Ubuntu (desktop)
        run: |
          mkdir -p build
          cd build
          conan install .. --build=missing -s compiler=gcc -s compiler.version=9 -s compiler.libcxx=libstdc++11 -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True
          cmake -DCMAKE_BUILD_TYPE=Release ..

      - name: Package code
        run: |
          cd build/
          cpack -G TGZ

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Linux
          path: |
            ${{ github.workspace }}/build/R-Type-*-Linux.tar.gz

  build-on-windows:
    runs-on: windows-latest
    steps:
      - name: Cache Conan packages
        id: cache_windows
        uses: actions/cache@v3
        with:
          path: |
            ~/.conan
            C:\.conan
          key: ${{ runner.os }}-CreateRelease-${{ hashfiles('**/conanfile.txt') }}

      - name: Install conan
        uses: turtlebrowser/get-conan@main

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Build rtype binaries on Ubuntu (desktop)
        run: |
          mkdir -p build
          cd build/
          conan install .. --build=missing -c tools.system.package_manager:mode=install -c tools.system.package_manager:sudo=True
          cmake -DCMAKE_BUILD_TYPE=Release -D_WIN32_WINNT=0x0601 ..

      - name: Package
        run: |
          cd build/
          cpack -G WIX -C Debug

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows
          path: |
            ${{ github.workspace }}/build/R-Type-*-win64.msi
  publish:
    runs-on: ubuntu-latest
    needs: [build-on-windows, build-on-ubuntu]
    permissions:
      contents: write
    environment:
      name: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3

      - name: Debug list directory
        shell: bash
        run: |
          ls -lRa
      # - name: Upload release binaries
      #   id: upload_release_asset
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     gh release create "${{ github.event.inputs.version }}" -t "${{ github.event.inputs.version }}"  -n "${{ github.event.inputs.body }}" ${{ github.workspace }}/ubuntu-latest/* ${{ github.workspace }}/windows-latest/*
